---
- name: test if unbound_version is set correctly
  assert:
    that:
      - unbound_version is defined
    quiet: yes

- name: test if unbound_temporary_directory is set correctly
  assert:
    that:
      - unbound_temporary_directory is defined
    quiet: yes

- name: test if unbound_interface is set correctly
  assert:
    that:
      - unbound_interface is defined
    quiet: yes

- name: test if unbound_port is set correctly
  assert:
    that:
      - unbound_port is defined
      - unbound_port is number
      - unbound_port | int > 0
      - unbound_port | int < 65536
    quiet: yes
