---
# handlers file for unbound
- name: configure
  command: ./configure --enable-systemd
  args:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"
    creates: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}/Makefile"

- name: make
  make:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"

- name: make install
  make:
    chdir: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}"
    target: install

- name: install service
  copy:
    src: "{{ unbound_temporary_directory }}/unbound-{{ unbound_version }}/contrib/unbound.service.in"
    dest: /etc/systemd/system/unbound.service
    remote_src: yes
    mode: "0755"
  notify:
    - systemctl daemon-reload

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart unbound
  service:
    name: unbound
    state: restarted
