---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _nslookup_package:
      default:
        - bind-utils
      Debian:
        - dnsutils

    nslookup_package: "{{ _nslookup_package[ansible_os_family] | default(_nslookup_package['default']) }}"

  tasks:
    - name: Install nslookup
      ansible.builtin.package:
        name: "{{ nslookup_package }}"
        state: present
      notify:
        - remove nslookup

    - name: Nslookup robertdebock.nl
      ansible.builtin.command:
        cmd: nslookup robertdebock.nl

  handlers:

    - name: Remove nslookup
      ansible.builtin.package:
        name: "{{ nslookup_package }}"
        state: absent
